// Bibelverse nach Schlachter 2000 (Wortlaut einzelner Verse bitte bei Bedarf prüfen)
// Themen: durchhalten, vertrauen, koerper, weisheit, seele, fundament
const VERSES = [
  { ref: "Matthäus 7,24-25", theme: "fundament", text: "Ein jeder nun, der diese meine Worte hört und sie tut, den will ich mit einem klugen Mann vergleichen, der sein Haus auf den Felsen baute. Als nun der Platzregen fiel und die Wasserströme kamen und die Winde stürmten und an dieses Haus stießen, fiel es nicht; denn es war auf den Felsen gegründet." },
  { ref: "Josua 1,9", theme: "durchhalten", text: "Habe ich dir nicht geboten, dass du stark und mutig sein sollst? Sei unerschrocken und sei nicht verzagt; denn der HERR, dein Gott, ist mit dir überall, wo du hingehst!" },
  { ref: "Philipper 4,13", theme: "durchhalten", text: "Ich vermag alles durch den, der mich stark macht, Christus." },
  { ref: "Galater 6,9", theme: "durchhalten", text: "Lasst uns aber im Gutestun nicht müde werden; denn zu seiner Zeit werden wir auch ernten, wenn wir nicht ermatten." },
  { ref: "Jesaja 40,31", theme: "durchhalten", text: "Die aber auf den HERRN harren, kriegen neue Kraft, dass sie auffahren mit Flügeln wie Adler, dass sie laufen und nicht matt werden, dass sie wandeln und nicht müde werden." },
  { ref: "Sprüche 24,16", theme: "durchhalten", text: "Denn der Gerechte fällt siebenmal und steht wieder auf; aber die Gottlosen stürzen nieder im Unglück." },
  { ref: "1. Korinther 9,27", theme: "koerper", text: "Sondern ich bezwinge meinen Leib und beherrsche ihn, damit ich nicht anderen verkündige und selbst verwerflich werde." },
  { ref: "Hebräer 12,1", theme: "durchhalten", text: "Lasst uns mit Ausdauer laufen in dem Kampf, der vor uns liegt." },
  { ref: "Jakobus 1,12", theme: "durchhalten", text: "Glückselig ist der Mann, der die Anfechtung erduldet; denn nachdem er sich bewährt hat, wird er die Krone des Lebens empfangen, die der Herr denen verheißen hat, die ihn lieben." },
  { ref: "2. Timotheus 1,7", theme: "durchhalten", text: "Denn Gott hat uns nicht einen Geist der Furchtsamkeit gegeben, sondern der Kraft und der Liebe und der Zucht." },
  { ref: "Philipper 3,14", theme: "durchhalten", text: "Ich jage nach dem Ziel, dem Kampfpreis der himmlischen Berufung Gottes in Christus Jesus." },
  { ref: "Römer 5,3-4", theme: "durchhalten", text: "Wir rühmen uns auch in den Bedrängnissen, weil wir wissen, dass die Bedrängnis standhaftes Ausharren bewirkt, das Ausharren aber Bewährung, die Bewährung aber Hoffnung." },
  { ref: "Matthäus 6,33", theme: "vertrauen", text: "Trachtet vielmehr zuerst nach dem Reich Gottes und nach seiner Gerechtigkeit, so wird euch dies alles hinzugefügt werden!" },
  { ref: "Matthäus 6,34", theme: "vertrauen", text: "Darum sollt ihr euch nicht sorgen um den morgigen Tag; denn der morgige Tag wird für das Seine sorgen. Jedem Tag genügt seine eigene Plage." },
  { ref: "Philipper 4,6-7", theme: "vertrauen", text: "Sorgt euch um nichts; sondern in allem lasst durch Gebet und Flehen mit Danksagung eure Anliegen vor Gott kundwerden. Und der Friede Gottes, der allen Verstand übersteigt, wird eure Herzen und eure Gedanken bewahren in Christus Jesus!" },
  { ref: "Philipper 4,19", theme: "vertrauen", text: "Mein Gott aber wird allen euren Mangel ausfüllen nach seinem Reichtum in Herrlichkeit in Christus Jesus." },
  { ref: "Sprüche 3,5-6", theme: "vertrauen", text: "Vertraue auf den HERRN von ganzem Herzen und verlass dich nicht auf deinen Verstand; erkenne ihn auf allen deinen Wegen, so wird er deine Pfade ebnen." },
  { ref: "Psalm 37,5", theme: "vertrauen", text: "Befiehl dem HERRN deinen Weg, und vertraue auf ihn, so wird er es vollbringen." },
  { ref: "Psalm 55,23", theme: "vertrauen", text: "Wirf dein Anliegen auf den HERRN, und er wird für dich sorgen; er wird den Gerechten in Ewigkeit nicht wanken lassen!" },
  { ref: "1. Petrus 5,7", theme: "vertrauen", text: "Alle eure Sorge werft auf ihn; denn er sorgt für euch." },
  { ref: "Matthäus 11,28", theme: "seele", text: "Kommt her zu mir alle, die ihr mühselig und beladen seid, so will ich euch erquicken!" },
  { ref: "Psalm 23,1", theme: "vertrauen", text: "Der HERR ist mein Hirte; mir wird nichts mangeln." },
  { ref: "Sprüche 10,4", theme: "vertrauen", text: "Lässige Hand macht arm, aber die Hand der Fleißigen macht reich." },
  { ref: "Sprüche 21,5", theme: "weisheit", text: "Die Pläne des Fleißigen bringen Gewinn, wer aber allzu sehr eilt, hat nur Mangel." },
  { ref: "2. Korinther 9,8", theme: "vertrauen", text: "Gott aber ist mächtig, euch jede Gnade im Überfluss zu spenden, sodass ihr in allem allezeit alle Genüge habt und überreich seid zu jedem guten Werk." },
  { ref: "Psalm 127,2", theme: "seele", text: "Es ist umsonst, dass ihr früh aufsteht und spät aufbleibt und sauer erworbenes Brot esst; solches gibt er seinem Geliebten im Schlaf!" },
  { ref: "1. Korinther 6,19-20", theme: "koerper", text: "Oder wisst ihr nicht, dass euer Leib ein Tempel des in euch wohnenden Heiligen Geistes ist? Denn ihr seid teuer erkauft; darum verherrlicht Gott in eurem Leib!" },
  { ref: "1. Korinther 3,16", theme: "koerper", text: "Wisst ihr nicht, dass ihr Gottes Tempel seid, und dass der Geist Gottes in euch wohnt?" },
  { ref: "Römer 12,1", theme: "koerper", text: "Ich ermahne euch nun, ihr Brüder, angesichts der Barmherzigkeit Gottes, dass ihr eure Leiber darbringt als ein lebendiges, heiliges, Gott wohlgefälliges Opfer: Das sei euer vernünftiger Gottesdienst!" },
  { ref: "1. Timotheus 4,8", theme: "koerper", text: "Denn die leibliche Übung ist nur zu wenigem nütze; die Gottesfurcht aber ist zu allen Dingen nütze, weil sie die Verheißung dieses und des zukünftigen Lebens hat." },
  { ref: "Psalm 139,14", theme: "koerper", text: "Ich danke dir dafür, dass ich erstaunlich und wunderbar gemacht bin; wunderbar sind deine Werke, und meine Seele erkennt das wohl!" },
  { ref: "Psalm 119,105", theme: "weisheit", text: "Dein Wort ist meines Fußes Leuchte und ein Licht auf meinem Weg." },
  { ref: "Josua 1,8", theme: "weisheit", text: "Lass dieses Buch des Gesetzes nicht von deinem Mund weichen, sondern forsche darin Tag und Nacht, damit du darauf achtest, alles zu befolgen, was darin geschrieben steht; denn dann wirst du Gelingen haben auf deinen Wegen, und dann wirst du weise handeln!" },
  { ref: "Sprüche 4,7", theme: "weisheit", text: "Der Anfang der Weisheit ist: Erwirb Weisheit, und um allen deinen Erwerb erwirb Verstand!" },
  { ref: "Sprüche 1,7", theme: "weisheit", text: "Die Furcht des HERRN ist der Anfang der Erkenntnis; nur Toren verachten Weisheit und Zucht!" },
  { ref: "Kolosser 3,23", theme: "weisheit", text: "Und alles, was ihr tut, das tut von Herzen, als für den Herrn und nicht für Menschen." },
  { ref: "Jakobus 1,5", theme: "weisheit", text: "Wenn es aber jemand unter euch an Weisheit mangelt, so erbitte er sie von Gott, der allen gern und ohne Vorwurf gibt, so wird sie ihm gegeben werden." },
  { ref: "Psalm 1,2-3", theme: "weisheit", text: "Glückselig ist der Mann, der seine Lust hat am Gesetz des HERRN und über sein Gesetz nachsinnt Tag und Nacht. Der ist wie ein Baum, gepflanzt an Wasserbächen, der seine Frucht bringt zu seiner Zeit, und alles, was er tut, gerät wohl." },
  { ref: "Römer 12,2", theme: "seele", text: "Und passt euch nicht diesem Weltlauf an, sondern lasst euch in eurem Wesen verwandeln durch die Erneuerung eures Sinnes, damit ihr prüfen könnt, was der gute und wohlgefällige und vollkommene Wille Gottes ist." },
  { ref: "Philipper 4,8", theme: "seele", text: "Im Übrigen, ihr Brüder, alles, was wahrhaftig, was ehrbar, was gerecht, was rein, was liebenswert, was wohllautend ist, wenn es irgendeine Tugend und etwas Lobenswertes gibt, darauf seid bedacht!" },
  { ref: "Psalm 118,24", theme: "seele", text: "Dies ist der Tag, den der HERR gemacht hat; wir wollen uns freuen und fröhlich sein in ihm!" },
  { ref: "Klagelieder 3,22-23", theme: "seele", text: "Gnadenbeweise des HERRN sind's, dass wir nicht gänzlich aufgerieben wurden, denn seine Barmherzigkeit ist nicht zu Ende; sie ist jeden Morgen neu, und deine Treue ist groß!" },
  { ref: "Psalm 121,1-2", theme: "vertrauen", text: "Ich hebe meine Augen auf zu den Bergen: Woher kommt mir Hilfe? Meine Hilfe kommt von dem HERRN, der Himmel und Erde gemacht hat!" },
  { ref: "Jesaja 41,10", theme: "vertrauen", text: "Fürchte dich nicht, denn ich bin mit dir; sei nicht ängstlich, denn ich bin dein Gott; ich stärke dich, ich helfe dir auch, ja, ich erhalte dich durch die rechte Hand meiner Gerechtigkeit!" },
  { ref: "Psalm 46,2", theme: "vertrauen", text: "Gott ist unsere Zuflucht und Stärke, eine Hilfe, bewährt in Nöten." },
  { ref: "Zephanja 3,17", theme: "seele", text: "Der HERR, dein Gott, ist in deiner Mitte, ein Held, der rettet; er wird sich über dich freuen mit Wonne, er wird schweigen in seiner Liebe, er wird über dich jubeln mit Jauchzen." },
  { ref: "Johannes 14,27", theme: "seele", text: "Frieden hinterlasse ich euch; meinen Frieden gebe ich euch. Nicht wie die Welt gibt, gebe ich euch; euer Herz erschrecke nicht und verzage nicht!" },
  { ref: "Psalm 91,1-2", theme: "vertrauen", text: "Wer im Schutz des Höchsten wohnt, der bleibt im Schatten des Allmächtigen. Ich sage zum HERRN: Meine Zuflucht und meine Burg, mein Gott, auf den ich vertraue!" },
  { ref: "Nehemia 8,10", theme: "seele", text: "Seid nicht bekümmert, denn die Freude am HERRN ist eure Stärke!" },
  { ref: "Psalm 127,1", theme: "fundament", text: "Wenn der HERR nicht das Haus baut, dann arbeiten umsonst, die daran bauen; wenn der HERR nicht die Stadt behütet, dann wacht der Wächter umsonst." },
  { ref: "Sprüche 16,3", theme: "fundament", text: "Befiehl dem HERRN deine Werke, so kommen deine Pläne zustande." },
  { ref: "Sprüche 16,9", theme: "fundament", text: "Das Herz des Menschen denkt sich seinen Weg aus, aber der HERR lenkt seine Schritte." },
  { ref: "Jeremia 29,11", theme: "fundament", text: "Denn ich weiß, was für Gedanken ich über euch habe, spricht der HERR, Gedanken des Friedens und nicht des Unheils, um euch eine Zukunft und eine Hoffnung zu geben." },
  { ref: "Psalm 90,12", theme: "weisheit", text: "Lehre uns unsere Tage richtig zählen, damit wir ein weises Herz erlangen!" },
  { ref: "Lukas 14,28", theme: "fundament", text: "Denn wer von euch, der einen Turm bauen will, setzt sich nicht zuvor hin und berechnet die Kosten, ob er die Mittel hat zur gänzlichen Ausführung?" },
  { ref: "Sprüche 6,6-8", theme: "durchhalten", text: "Geh hin zur Ameise, du Fauler, sieh ihre Wege an und werde weise: Obwohl sie keinen Fürsten hat, weder Aufseher noch Gebieter, bereitet sie dennoch im Sommer ihr Brot und sammelt in der Erntezeit ihre Speise." },
  { ref: "Galater 5,22-23", theme: "seele", text: "Die Frucht des Geistes aber ist Liebe, Freude, Friede, Langmut, Freundlichkeit, Güte, Treue, Sanftmut, Selbstbeherrschung." },
  { ref: "Psalm 34,9", theme: "seele", text: "Schmeckt und seht, wie freundlich der HERR ist; wohl dem, der auf ihn traut!" },
  { ref: "5. Mose 8,18", theme: "vertrauen", text: "Sondern du sollst an den HERRN, deinen Gott, denken; denn er ist es, der dir Kraft gibt, Reichtum zu erwerben." },
  { ref: "Matthäus 25,21", theme: "durchhalten", text: "Recht so, du guter und treuer Knecht! Du bist über wenigem treu gewesen, ich will dich über vieles setzen; geh ein zur Freude deines Herrn!" },
];

// Kurze Mittags-Impulse für den Aussendienst
const IMPULSES = [
  "Wasser statt Süssgetränk. Dein Leib ist ein Tempel. (1. Kor 6,19)",
  "Kein Tankstellen-Snack. Du bezwingst deinen Leib, nicht er dich. (1. Kor 9,27)",
  "Halbzeit. Sei stark und mutig – der HERR ist mit dir. (Jos 1,9)",
  "Der Fleissige plant und gewinnt. Nächster Kundentermin: voll da sein. (Spr 21,5)",
  "Auto-Zeit = Hörbuch statt Grübeln. Worauf richtest du deine Gedanken? (Phil 4,8)",
  "Ein Schritt nach dem anderen. Er lenkt deine Schritte. (Spr 16,9)",
  "Müde? Die auf den HERRN harren, kriegen neue Kraft. (Jes 40,31)",
  "Heute schon gedankt? Die Freude am HERRN ist deine Stärke. (Neh 8,10)",
  "Nicht sorgen – beten. Dann weiterarbeiten. (Phil 4,6)",
  "Disziplin ist ein Geschenk des Geistes: Kraft, Liebe, Selbstbeherrschung. (2. Tim 1,7)",
];

if (typeof module !== "undefined") module.exports = { VERSES, IMPULSES };
